# Generated by Django 3.2.7 on 2021-11-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='how_many',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
