# Generated by Django 3.2.7 on 2021-11-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_what_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='what_food',
            name='how_many',
        ),
        migrations.AlterField(
            model_name='what_food',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.people'),
        ),
    ]
