# Generated by Django 3.2.7 on 2021-11-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20211106_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='what_food',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
