# Generated by Django 3.2.7 on 2021-11-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_what_food_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='what_food',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
