# Generated by Django 3.2.7 on 2021-11-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_what_food_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='what_food',
            name='date',
            field=models.IntegerField(default=20211106),
        ),
    ]
