# Generated by Django 3.2.7 on 2021-11-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20211107_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
