# Generated by Django 3.2.7 on 2021-11-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20211107_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.IntegerField(default=1),
        ),
    ]
