# Generated by Django 3.2.7 on 2021-11-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_event_who'),
    ]

    operations = [
        migrations.CreateModel(
            name='who',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=1)),
            ],
        ),
    ]
